name: 'McAllister Idea Lab '
favicon: null
layout_spectrum: 0.1827957
typography_spectrum: 0.10387
title: 株式会社 マカリスター 考務店
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#27415D'
    - '#87A4B5'
    - '#CCF7FF'
    - '#D7B46E'
    - '#AB5D4B'
  brandStrength: 0.125
  lightness: 0.9301075
  saturation: 0.02329749
  rhythmicContrast: 0.2007169
purpose: []
