title: Ideas Matter
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.02329749
  brandStrength: 0.8082438
  lightness: 0.9301075
  brandColors:
    - '#27415D'
    - '#87A4B5'
    - '#CCF7FF'
    - '#D7B46E'
    - '#AB5D4B'
  rhythmicContrast: 0.2007169
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: 'McAllister Idea Lab '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8154122
layout_spectrum: 0.1827957
